Script started on Sat 17 Feb 2018 03:44:44 PM PST
yeseul90@uw1-320-12:~$ exitvalgrind ./lab3g++ graphl.cpp graphm.cpp lab3.cpp nodedata.cpp -g -o labb3
yeseul90@uw1-320-12:~$ g++ graphl.cpp graphm.cpp lab3.cpp nodedata.cpp -g -o labb3[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexit[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cvalgrind ./lab3
==20374== Memcheck, a memory error detector
==20374== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==20374== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==20374== Command: ./lab3
==20374== 
Description           From Node     To Node    Dijkstra's    Path
Aurora and 85th
                          1           2          40         1 3 2 
                          1           3          20         1 3 
                          1           4          50         1 3 2 4 
                          1           5          30         1 5 
Green Lake Starbucks
                          2           1        ----
                          2           3        ----
                          2           4          10         2 4 
                          2           5        ----
Woodland Park Zoo
                          3           1        ----
                          3           2          20         3 2 
                          3           4          30         3 2 4 
                          3           5        ----
Troll under bridge
                          4           1        ----
                          4           2        ----
                          4           3        ----
                          4           5        ----
PCC
                          5           1        ----
                          5           2          20         5 2 
                          5           3        ----
                          5           4          25         5 4 
      3        1       ----

      1        2         40              1 3 2 
Aurora and 85th
Woodland Park Zoo
Green Lake Starbucks

      1        4         50              1 3 2 4 
Aurora and 85th
Woodland Park Zoo
Green Lake Starbucks
Troll under bridge

Description           From Node     To Node    Dijkstra's    Path
aaa
                          1           2           9         1 3 2 
                          1           3           5         1 3 
bbb
                          2           1        ----
                          2           3          20         2 3 
ccc
                          3           1        ----
                          3           2           4         3 2 
      3        1       ----

      1        2          9              1 3 2 
aaa
ccc
bbb

      1        4       ----

Graph:
Node 1                Aurora and 85th
   edge 1 2 
   edge 1 3 
   edge 1 5 
Node 2                Green Lake Starbucks
   edge 2 4 
Node 3                Woodland Park Zoo
   edge 3 2 
   edge 3 4 
Node 4                Troll under bridge
Node 5                PCC
   edge 5 2 
   edge 5 4 

Depth-first ordering: 1 2 4 3 5 
Graph:
Node 1                aaa
   edge 1 3 
   edge 1 2 
Node 2                bbb
   edge 2 3 
Node 3                ccc
   edge 3 2 

Depth-first ordering: 1 3 2 

==20374== 
==20374== HEAP SUMMARY:
==20374==     in use at exit: 72,704 bytes in 1 blocks
==20374==   total heap usage: 35 allocs, 34 frees, 91,943 bytes allocated
==20374== 
==20374== LEAK SUMMARY:
==20374==    definitely lost: 0 bytes in 0 blocks
==20374==    indirectly lost: 0 bytes in 0 blocks
==20374==      possibly lost: 0 bytes in 0 blocks
==20374==    still reachable: 72,704 bytes in 1 blocks
==20374==         suppressed: 0 bytes in 0 blocks
==20374== Rerun with --leak-check=full to see details of leaked memory
==20374== 
==20374== For counts of detected and suppressed errors, rerun with: -v
==20374== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
yeseul90@uw1-320-12:~$ exit
exit

Script done on Sat 17 Feb 2018 03:44:54 PM PST
